"use client";

import { useMemo, useState } from "react";
import type { CompetencyDefinition, CompetencyLevel, DevelopmentAction } from "@/types/graduate-matrix";
import { reviewActionResponse } from "./action-response-quality";
import Modal from "./Modal";
import { RIBA_STAGES, ribaStageLabel } from "./useMatrixPoc";
import type { PocAction, PocActionResponse, PocResponseMethod, PocResponseStatus, PocResponseVersion, PocRibaStage, useMatrixPoc } from "./useMatrixPoc";

type PocApi = ReturnType<typeof useMatrixPoc>;
type Action = DevelopmentAction | PocAction;
type Attachment = PocResponseVersion["attachments"][number];
type DocumentLink = PocResponseVersion["documentLinks"][number];
type Prompt = { key:string; label:string; words:string; hint:string; placeholder?:string };
type Method = { value:PocResponseMethod; label:string; explanation:string; prompts:Prompt[]; example:{ heading:string; sections:{ label:string; text:string }[] } };

const METHODS: Method[] = [
  { value:"carr", label:"CAR+R", explanation:"Good for normal responses where you need to explain what happened, what you personally did and what changed.", prompts:[{key:"context",label:"Context",words:"60–120 words",hint:"Set out the project context, your role and the technical situation."},{key:"action",label:"Action",words:"100–220 words",hint:"Explain what you personally did. Use ‘I’, not ‘we’. Include checks, coordination, judgement and decisions."},{key:"result",label:"Result",words:"50–120 words",hint:"State what changed because of your action, including technical, programme, quality or compliance outcomes."},{key:"reflection",label:"Reflection",words:"80–160 words",hint:"Explain what you learned, what you would do differently and how this will improve your future work."}], example:{heading:"Example · CAR+R structure (L2 entry on B2)",sections:[{label:"Context",text:"On project PRJ-2024-014 (mid-rise office refurb), I was asked by the senior engineer to size the new chilled water pipework for the cooling loop serving floors 3–5."},{label:"Action",text:"I extracted the cooling loads from the IES VE model (peak 142 kW) and used the chiller manufacturer's flow rate (5.4 l/s for 6°C ΔT). I calculated pipe sizes for each branch using CIBSE Guide C tables, targeting 1–2 m/s velocity and ≤300 Pa/m pressure drop. I selected DN65 for the main risers and stepped down to DN40–DN32 for the branches. I produced a marked-up plant schematic and a pipe schedule which I checked with the senior engineer."},{label:"Result",text:"The senior engineer reviewed and amended two branch sizes because I had not accounted for diversity in the original sizing assumption. The schedule was issued at RIBA Stage 3."},{label:"Reflection",text:"I learned that diversity factors are critical when sizing branch pipework, not just at plant level. Next time I will document my diversity assumptions explicitly in the calculation sheet and ask my senior to review my assumptions list before doing the sizing."}]} },
  { value:"star", label:"STAR", explanation:"Good for interview-style responses and behavioural competences. It separates the situation from your personal responsibility.", prompts:[{key:"situation",label:"Situation",words:"50–100 words",hint:"Describe the project background, technical issue, constraint or setting."},{key:"task",label:"Task",words:"40–90 words",hint:"State what you were personally responsible for, separate from the wider team."},{key:"action",label:"Action",words:"120–240 words",hint:"Explain the specific steps, decisions, checks, coordination or calculations you carried out."},{key:"result",label:"Result",words:"50–120 words",hint:"Explain the outcome, decision, deliverable, risk reduction, improvement or feedback received."},{key:"reflection",label:"Reflection",words:"80–160 words",hint:"Explain what you learned and what you would do differently next time."}], example:{heading:"Example · STAR structure (L3 entry on C1 / project delivery)",sections:[{label:"Situation",text:"On project PRJ-2024-033, the Stage 3 mechanical design package was due in two weeks and the architectural layout had changed, affecting the riser sizes and plantroom access routes."},{label:"Task",text:"I was responsible for updating the ventilation coordination mark-ups, checking that the revised duct routes still allowed access for maintenance, and reporting any risks to the senior engineer before the design team meeting."},{label:"Action",text:"I reviewed the latest architectural drawings, marked up the affected risers in Bluebeam, checked duct sizes against the airflow schedule, and identified two locations where the access panels would be blocked by new joinery. I prepared a short issue schedule with screenshots, proposed revised access zones, and talked the architect through the problem before the coordination meeting."},{label:"Result",text:"The architect amended the joinery layout before the package was issued, avoiding a late site change. My senior engineer accepted the issue schedule as evidence of coordination and asked me to use the same format on the next project."},{label:"Reflection",text:"I learned that a clear issue schedule is more useful than a long email because it makes ownership and required action obvious. Next time I will raise access and maintenance constraints earlier when layouts are still flexible."}]} },
  { value:"psar", label:"PSAR", explanation:"Best for L4/L5 responses demonstrating judgement, complexity, leadership, innovation or strategic decision-making.", prompts:[{key:"problem",label:"Problem",words:"60–120 words",hint:"Define the complex, unfamiliar, ambiguous or higher-risk problem and its constraints."},{key:"solution",label:"Solution",words:"100–220 words",hint:"Explain the options considered, technical rationale and why the preferred approach was selected."},{key:"action",label:"Action",words:"100–220 words",hint:"Explain what you led, developed, coordinated, challenged, improved or decided."},{key:"result",label:"Result",words:"50–120 words",hint:"State the impact, including improved decisions, risk reduction, performance or deliverable quality."},{key:"reflection",label:"Reflection",words:"80–180 words",hint:"Explain what you learned about judgement, leadership, uncertainty, trade-offs or innovation."}], example:{heading:"Example · PSAR structure (L4 entry on A2 / CEng track)",sections:[{label:"Problem",text:"On PRJ-2024-021 (heritage school retrofit), the existing gas boilers were end-of-life and the client wanted to electrify heating, but the existing electrical incomer had insufficient capacity for a straightforward ASHP solution. A full incomer upgrade was expensive and would have pushed the project outside the budget."},{label:"Solution",text:"I led an option study comparing ASHP with supplementary direct electric, hybrid ASHP/gas, and a ground-source option with lower electrical peak demand. I judged the ground-source option as the best route because it reduced the peak electrical load while supporting the client's decarbonisation brief. I compared whole-life carbon and operational cost over 25 years against the alternatives."},{label:"Action",text:"I coordinated the geotechnical input, developed the heat pump and buffer vessel strategy, presented the preferred option to the client, and reviewed the associated electrical load assessment with the electrical engineer."},{label:"Reflection",text:"The key insight was that the constraint became the design driver, not a barrier. With hindsight, I would have started the borehole feasibility work earlier because waiting for the test results delayed Stage 3 sign-off. This entry demonstrates judgement, ownership of an unfamiliar problem, and coordination across disciplines."}]} },
  { value:"short-update", label:"Short update", explanation:"Use for a concise interim update. It is not a substitute for a complete final response.", prompts:[{key:"progress",label:"Progress update",words:"30–100 words",hint:"State specifically what you have completed or changed."},{key:"blockers",label:"Blockers",words:"Optional",hint:"Record any constraint or help needed. Leave blank if there is no blocker."},{key:"nextStep",label:"Next step",words:"20–80 words",hint:"State the next concrete action and, where possible, when it will happen."}], example:{heading:"Example · Short update (new app addition)",sections:[{label:"Progress update",text:"I reviewed the latest ventilation drawings, completed the initial airflow check and recorded two coordination queries for the architect."},{label:"Blockers",text:"I am waiting for confirmation of the revised occupancy schedule."},{label:"Next step",text:"Once confirmed, I will update the calculation and issue the marked-up drawing for mentor review by Friday."}]} },
];

const PLACEHOLDERS: Record<PocResponseMethod, Record<string, string>> = {
  carr: {
    context: "Example: I was working on a Stage 3 ventilation strategy for a school refurbishment. My role was to support the senior engineer by checking the existing plant capacity and identifying the main risks...",
    action: "Example: I reviewed the existing drawings, compared the proposed occupancy against the ventilation allowances, marked up the riser constraints, and prepared a short options note...",
    result: "Example: The review identified that the proposed AHU duty was short by approximately 15%, so the team agreed to revise the plant selection before Stage 3 issue...",
    reflection: "Example: I learned that checking occupancy assumptions early is as important as checking plant duty. Next time, I would confirm the briefing assumptions before starting the calculation...",
  },
  star: {
    situation: "Example: The project was a live school refurbishment where the proposed science lab layout changed late in Stage 3. This affected ventilation rates, fume cupboard extract, and ceiling coordination...",
    task: "Example: My task was to check whether the revised layout could be served by the current ventilation strategy and to identify any risks that needed to be escalated to the senior engineer...",
    action: "Example: I recalculated the extract requirement, checked the duct route against the ceiling zone, reviewed the control philosophy, and coordinated the riser impact with the architect...",
    result: "Example: The review showed that one branch duct needed to be increased and the ceiling access strategy needed to be adjusted. The issue was picked up before tender issue...",
    reflection: "Example: This helped me understand that late layout changes can affect several MEP interfaces at once. In future, I would raise an explicit ventilation impact check whenever room layouts change...",
  },
  psar: {
    problem: "Example: The client wanted to reduce operational carbon, but the existing electrical capacity limited the viable heat pump options and the plantroom had restricted access...",
    solution: "Example: I compared a direct ASHP replacement, hybrid boiler/ASHP operation, and a lower-temperature distribution strategy. I recommended the hybrid strategy because...",
    action: "Example: I led the option appraisal, coordinated the electrical load review, prepared the risk register updates, and presented the preferred approach to the design team...",
    result: "Example: The option appraisal allowed the client to proceed without an immediate supply upgrade and gave the design team a clear Stage 4 development route...",
    reflection: "Example: I learned that the best technical answer is not always the largest equipment selection. The stronger solution was the one that balanced capacity, risk, cost, and future flexibility...",
  },
  "short-update": {
    progress: "Example: I completed the initial design check and issued two coordination queries.",
    blockers: "Example: I am waiting for the revised occupancy schedule.",
    nextStep: "Example: I will update the calculation and issue it for review by Friday.",
  },
};

const formatBytes=(size?:number)=>size===undefined?"":size<1024?`${size} B`:size<1048576?`${(size/1024).toFixed(1)} KB`:`${(size/1048576).toFixed(1)} MB`;
const isPoc=(action:Action):action is PocAction=>"source" in action;

export default function CandidateActionResponseModal({ action, competency, candidateId, currentLevel, poc, onClose }:{ action:Action; competency:CompetencyDefinition; candidateId:string; currentLevel:CompetencyLevel|null; poc:PocApi; onClose:()=>void }) {
  const response=poc.state.responses.find((entry)=>entry.actionId===action.id); const previous=response?.versions.at(-1)??null;
  const [method,setMethod]=useState<PocResponseMethod>(previous?.method??((currentLevel==="L4"||currentLevel==="L5")?"psar":"carr"));
  const [fields,setFields]=useState<Record<string,string>>(previous?.fields??{}); const [attachments,setAttachments]=useState<Attachment[]>(previous?.attachments??[]); const [documentLinks,setDocumentLinks]=useState<DocumentLink[]>(previous?.documentLinks??[]);
  const [showExample,setShowExample]=useState(false); const [showLink,setShowLink]=useState(false); const [link,setLink]=useState({title:"",url:"",reference:"",revision:"",accessNote:""}); const [message,setMessage]=useState<string|null>(null);
  const [initialState]=useState(()=>JSON.stringify({method:previous?.method??((currentLevel==="L4"||currentLevel==="L5")?"psar":"carr"),fields:previous?.fields??{},attachments:previous?.attachments??[],documentLinks:previous?.documentLinks??[]}));
  const selected=METHODS.find((entry)=>entry.value===method)??METHODS[0]; const quality=useMemo(()=>reviewActionResponse({method,fields}),[method,fields]);
  const hasNarrative=selected.prompts.some((item)=>fields[item.key]?.trim()); const returned=previous?.status==="returned"||action.status==="returned-for-revision"; const latestReview=previous?poc.state.responseReviews.find((entry)=>entry.responseVersionId===previous.id):undefined; const submitted=latestReview?.outcome==="accepted";
  const description=isPoc(action)?action.description:action.notes||"No supporting detail recorded."; const expected=isPoc(action)?action.expectedEvidence:"Complete the action in line with the mentor’s instructions.";
  const displayId=`${competency.reference}-${action.id.startsWith("local-poc")?action.id.split("-").at(-1)?.toUpperCase():action.id.slice(0,6).toUpperCase()}`;
  const dirty=initialState!==JSON.stringify({method,fields,attachments,documentLinks});
  const requestClose=()=>{if(!submitted&&dirty&&!window.confirm("Discard your unsaved response changes?"))return;onClose();};
  const addFiles=(files:FileList|null)=>{if(files)setAttachments((current)=>[...current,...Array.from(files).map((file,index)=>({id:`local-poc-file-${Date.now()}-${index}`,kind:"file" as const,name:file.name,detail:file.type||"File",size:file.size}))]);};
  const addLink=()=>{if(!link.title.trim()||!link.url.trim()){setMessage("Enter a document title and URL.");return;} try{new URL(link.url);}catch{setMessage("Enter a valid document URL.");return;} setDocumentLinks((current)=>[...current,{id:`local-poc-link-${Date.now()}`,kind:"link",...link}]);setLink({title:"",url:"",reference:"",revision:"",accessNote:""});setShowLink(false);setMessage(null);};
  const setRibaStage=(value:string)=>{poc.commit((state)=>({...state,actions:state.actions.map((entry)=>entry.id===action.id?{...entry,ribaStage:(value||null) as PocRibaStage|null,updatedAt:new Date().toISOString()}:entry)}))};
  const save=(status:PocResponseStatus)=>{if(!hasNarrative){setMessage("Enter at least one response section before saving.");return;} const required=method==="short-update"?["progress","nextStep"]:["action","result","reflection"]; if(status==="submitted"&&!required.every((key)=>fields[key]?.trim())){setMessage(method==="short-update"?"Complete Progress update and Next step before submitting.":"Complete Action, Result and Reflection before submitting.");return;} const now=new Date().toISOString(); const version:PocResponseVersion={id:`local-poc-response-version-${Date.now()}`,version:(response?.versions.length??0)+1,status,method,fields,attachments,documentLinks,savedAt:now,submittedAt:status==="submitted"?now:null,advisoryQualityScore:quality.score}; poc.commit((state)=>{const current=state.responses.find((entry)=>entry.actionId===action.id);const next:PocActionResponse=current?{...current,versions:[...current.versions,version],updatedAt:now}:{id:`local-poc-response-${Date.now()}`,source:"local-poc",candidateId,actionId:action.id,competencyRef:competency.reference,versions:[version],updatedAt:now};return{...state,responses:[...state.responses.filter((entry)=>entry.actionId!==action.id),next],actions:state.actions.map((entry)=>entry.id===action.id?{...entry,status:status==="submitted"?"submitted":entry.status,updatedAt:now}:entry)}});onClose();};
  return <Modal title="Respond to Development Action" size="response" onClose={requestClose} footer={submitted?<button type="button" className="btn-ghost" onClick={onClose}>Close</button>:<><button type="button" className="btn-ghost" onClick={requestClose}>Cancel</button><span className="response-footer-status" role="status" aria-live="polite">{message}</span><button type="button" className="btn-secondary" onClick={()=>save("draft")}>{returned?"Save revised draft":"Save draft"}</button><button type="button" className="btn-primary" onClick={()=>save("submitted")}>{returned?"Resubmit":"Submit for review"}</button></>}>
    <div className="action-response-form"><div className="action-comment-subtitle">{displayId} · {action.title}</div>
      <section className="action-response-section"><h3>Action brief</h3><div className="action-brief-grid"><div className="wide"><span>Action</span><strong>{displayId} · {action.title}</strong></div><div className="wide"><span>Description</span><strong>{description}</strong></div><div className="wide"><span>Expected outcome</span><strong>{expected}</strong></div><div><span>Due</span><strong>{action.dueDate||"Not set"}</strong></div><div><span>Priority</span><strong>{action.priority}</strong></div><div><span>Assigned by</span><strong>{isPoc(action)?"Mentor (local POC)":action.createdBy||"Mentor"}</strong></div><div><span>Owner</span><strong>{action.owner}</strong></div><div className="wide"><span>Competency</span><strong>{competency.reference} · {competency.area}</strong></div><div className="wide"><span>Active cycle</span><strong>{currentLevel??"Not initialised"}</strong></div><div className="wide"><span>RIBA Design Stage</span>{isPoc(action)?<select disabled={submitted} value={action.ribaStage??""} onChange={(event)=>setRibaStage(event.target.value)}><option value="">Not set</option>{RIBA_STAGES.map((stage)=><option key={stage} value={stage}>{ribaStageLabel(stage)}</option>)}</select>:<strong>Not set</strong>}</div></div></section>
      <section className="action-response-section"><div className="response-section-heading"><h3>Response structure</h3><button type="button" className="btn-ghost" aria-expanded={showExample} onClick={()=>setShowExample((current)=>!current)}>{showExample?"Hide example":"Show example"}</button></div><div className="response-method-tabs" role="tablist" aria-label="Response structure">{METHODS.map((entry)=><button disabled={submitted} type="button" role="tab" aria-selected={method===entry.value} className={method===entry.value?"active":""} onClick={()=>setMethod(entry.value)} key={entry.value}>{entry.label}</button>)}</div><p className="response-guidance">{selected.explanation}</p><div className="response-learning-banner">Fill each section separately. The tool compiles the sections into one development action response.</div>{showExample?<aside className="response-worked-example"><strong>{selected.example.heading}</strong>{selected.example.sections.map((section)=><p key={section.label}><b>{section.label}:</b> {section.text}</p>)}</aside>:null}</section>
      <section className="action-response-section"><h3>Structured response</h3><div className="original-structured-fields">{selected.prompts.map((item)=><label key={item.key}><strong>{item.label} <small>{item.words}</small></strong><em>{item.hint}</em><textarea readOnly={submitted} placeholder={item.placeholder??PLACEHOLDERS[method][item.key]} rows={4} value={fields[item.key]??""} onChange={(event)=>setFields((current)=>({...current,[item.key]:event.target.value}))}/></label>)}</div></section>
      <section className="quality-reviewer"><div><h3>Writing quality reviewer</h3>{hasNarrative?<strong className={`quality-label quality-${quality.score}`}>{quality.label}</strong>:null}</div>{hasNarrative?<><ul>{quality.checks.map((check)=><li className={check.state} key={check.id}><span aria-hidden="true">{check.state==="met"?"✓":"!"}</span>{check.label}</li>)}</ul><small>{quality.wordCount} words in the active response structure.</small></>:<p>Start writing to receive structured feedback.</p>}<p>Writing guidance only — your mentor makes the final review decision.</p></section>
      <section className="action-response-section"><h3>Supporting files</h3>{!submitted?<div className="supporting-file-actions"><label className="btn-secondary">Upload files<input type="file" multiple onChange={(event)=>addFiles(event.target.files)}/></label><button type="button" className="btn-secondary" onClick={()=>setShowLink((current)=>!current)}>Add document link</button></div>:null}{showLink&&!submitted?<div className="response-document-link-form"><label>Title<input value={link.title} onChange={(e)=>setLink({...link,title:e.target.value})}/></label><label>URL<input type="url" value={link.url} onChange={(e)=>setLink({...link,url:e.target.value})}/></label><label>Reference<input value={link.reference} onChange={(e)=>setLink({...link,reference:e.target.value})}/></label><label>Revision<input value={link.revision} onChange={(e)=>setLink({...link,revision:e.target.value})}/></label><label className="wide">Access note<input value={link.accessNote} onChange={(e)=>setLink({...link,accessNote:e.target.value})}/></label><button type="button" className="btn-primary" onClick={addLink}>Add link</button></div>:null}<div className="response-attachment-list">{attachments.map((item)=><div key={item.id}><span><b>{item.name}</b><small>{item.detail} · {formatBytes(item.size)}</small></span>{!submitted?<button type="button" className="btn-ghost" onClick={()=>setAttachments((current)=>current.filter((entry)=>entry.id!==item.id))}>Remove</button>:null}</div>)}{documentLinks.map((item)=><div key={item.id}><span><b>{item.title}</b><small>{item.reference||"Document link"}{item.revision?` · ${item.revision}`:""}</small></span><a className="btn-ghost" href={item.url} target="_blank" rel="noreferrer">Open</a>{!submitted?<button type="button" className="btn-ghost" onClick={()=>setDocumentLinks((current)=>current.filter((entry)=>entry.id!==item.id))}>Remove</button>:null}</div>)}</div><p className="response-guidance">Selected file metadata is stored locally. File contents are not retained after refresh.</p></section>
    </div>
  </Modal>;
}

export function MentorResponseSummary({response}:{response:PocActionResponse}){const version=response.versions.at(-1);if(!version)return null;const method=METHODS.find((entry)=>entry.value===version.method);const fileCount=version.attachments?.length??0;const linkCount=version.documentLinks?.length??0;return <section className="record-detail-copy"><strong>Candidate response · Version {version.version} · {version.status}</strong><div className="mentor-structured-response">{method?.prompts.map((item)=>version.fields[item.key]?.trim()?<div key={item.key}><b>{item.label}</b><p>{version.fields[item.key]}</p></div>:null)}</div>{fileCount||linkCount?<p>{fileCount} file{fileCount===1?"":"s"} and {linkCount} document link{linkCount===1?"":"s"} supplied.</p>:null}</section>}
