"use client";

import { useRef, useState } from "react";
import { archiveAction } from "@/app/portfolio-actions";
import type { CompetencyDefinition, CompetencyLevel, DevelopmentAction } from "@/types/graduate-matrix";
import Modal from "./Modal";
import { RIBA_STAGES, ribaStageLabel } from "./useMatrixPoc";
import type { PocAction, PocActionResponseReview, PocActionResponseReviewOutcome, PocResponseMethod, PocResponseVersion, PocRibaStage, useMatrixPoc } from "./useMatrixPoc";

type PocApi=ReturnType<typeof useMatrixPoc>; type Action=DevelopmentAction|PocAction;
const methodLabels:Record<PocResponseMethod,string>={carr:"CAR+R",star:"STAR",psar:"PSAR","short-update":"Short update"};
const methodFields:Record<PocResponseMethod,{key:string;label:string;optional?:boolean}[]>={carr:[{key:"context",label:"Context"},{key:"action",label:"Action"},{key:"result",label:"Result"},{key:"reflection",label:"Reflection"}],star:[{key:"situation",label:"Situation"},{key:"task",label:"Task"},{key:"action",label:"Action"},{key:"result",label:"Result"},{key:"reflection",label:"Reflection"}],psar:[{key:"problem",label:"Problem"},{key:"solution",label:"Solution"},{key:"action",label:"Action"},{key:"result",label:"Result"},{key:"reflection",label:"Reflection"}],"short-update":[{key:"progress",label:"Progress update"},{key:"blockers",label:"Blockers",optional:true},{key:"nextStep",label:"Next step"}]};
const isPoc=(action:Action):action is PocAction=>"source" in action; const date=(value?:string|null)=>value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Not recorded";
const validUrl=(value:string)=>{try{const url=new URL(value);return url.protocol==="https:"||url.protocol==="http:"}catch{return false}};

export default function MentorActionResponseReviewModal({action,competency,currentLevel,candidateId,canUseServerMentorActions,poc,onClose}:{action:Action;competency:CompetencyDefinition;currentLevel:CompetencyLevel|null;candidateId:string;canUseServerMentorActions:boolean;poc:PocApi;onClose:()=>void}){
  const local=isPoc(action);
  const actionDescription=local?action.description:action.notes||"No description recorded."; const success=local?action.expectedEvidence:"Complete the assigned action and meet the recorded success criteria."; const displayId=`${competency.reference}-${action.id.startsWith("local-poc")?"A01":action.id.slice(0,6).toUpperCase()}`;
  const response=poc.state.responses.find((entry)=>entry.actionId===action.id); const submitted=response?.versions.filter((entry)=>entry.status==="submitted"||entry.status==="returned").at(-1); const [viewVersion,setViewVersion]=useState<PocResponseVersion|null>(submitted??null);
  const existingReview=submitted?poc.state.responseReviews.find((entry)=>entry.responseVersionId===submitted.id):undefined; const existingOutcome: ""|"accept"|"keep-open"=existingReview?.outcome==="accepted"?"accept":existingReview?.outcome==="kept-open"?"keep-open":"";
  const [historyOpen,setHistoryOpen]=useState(false); const [feedback,setFeedback]=useState(existingReview?.feedback??""); const [outcome,setOutcome]=useState<""|"accept"|"keep-open">(existingOutcome); const [afterAccept,setAfterAccept]=useState<"keep-open"|"complete">(existingReview?.completeAction?"complete":"keep-open"); const [message,setMessage]=useState<string|null>(null); const [saving,setSaving]=useState(false); const feedbackRef=useRef<HTMLTextAreaElement>(null); const outcomeRef=useRef<HTMLSelectElement>(null);
  const reviewed=Boolean(existingReview); const initial=`${existingReview?.feedback??""}|${existingOutcome}|${existingReview?.completeAction?"complete":"keep-open"}`; const dirty=!reviewed&&`${feedback}|${outcome}|${afterAccept}`!==initial; const requestClose=()=>{if(dirty&&!window.confirm("Discard your unsaved mentor review?"))return;onClose()};

  const deleteLocal=()=>{poc.commit((state)=>({...state,actions:state.actions.filter((entry)=>entry.id!==action.id)}));onClose();};
  const confirmDeleteLocal=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(window.confirm("Delete this development action? This cannot be undone."))deleteLocal();};
  const deleteControl=local?<form className="record-modal-actions" onSubmit={confirmDeleteLocal}><button type="submit" className="btn-danger">Delete action</button></form>:canUseServerMentorActions?<form action={archiveAction} className="record-modal-actions"><input type="hidden" name="candidateId" value={candidateId}/><input type="hidden" name="actionId" value={action.id}/><input type="hidden" name="reason" value="Removed from the active action plan by the mentor."/><button className="btn-danger">Delete action</button></form>:null;

  const setRibaStage=(value:string)=>{poc.commit((state)=>({...state,actions:state.actions.map((entry)=>entry.id===action.id?{...entry,ribaStage:(value||null) as PocRibaStage|null,updatedAt:new Date().toISOString()}:entry)}))};
  const ribaControl=local?<div><span>RIBA Design Stage</span><select value={action.ribaStage??""} onChange={(event)=>setRibaStage(event.target.value)}><option value="">Not set</option>{RIBA_STAGES.map((stage)=><option key={stage} value={stage}>{ribaStageLabel(stage)}</option>)}</select></div>:<div><span>RIBA Design Stage</span><strong>Not set</strong></div>;

  if(!response||!submitted||!viewVersion)return <Modal title="Review Development Action" size="mentor-review" onClose={onClose} footer={<button className="btn-ghost" onClick={onClose}>Close</button>}>
    <div className="mentor-review-form"><div className="action-comment-subtitle">{displayId} · {action.title}</div>
      <section className="mentor-review-section"><h3>Action brief</h3><div className="record-detail"><div><span>Owner</span><strong>{action.owner}</strong></div><div><span>Priority</span><strong>{action.priority}</strong></div><div><span>Due date</span><strong>{action.dueDate||"Not set"}</strong></div><div><span>Status</span><strong>{action.status.replaceAll("-"," ")}</strong></div>{ribaControl}</div><div className="mentor-review-copy"><strong>Action / success criteria</strong><p>{actionDescription}</p><p>{success}</p><small>{competency.reference} · {competency.area} · Active cycle {currentLevel||"not initialised"} · Assigned {date(action.createdAt)}</small></div></section>
      <p className="record-empty-copy">No candidate response has been submitted for this action yet.</p>
      {deleteControl}
    </div>
  </Modal>;

  const fields=methodFields[viewVersion.method]??Object.keys(viewVersion.fields).map((key)=>({key,label:key.replaceAll("-"," ")})); const reviews=poc.state.responseReviews.filter((entry)=>entry.actionId===action.id);
  const buttonLabel=outcome==="accept"?(afterAccept==="complete"?"Accept & complete action":"Accept response"):outcome==="keep-open"?"Save review & keep action open":"Select an outcome";
  const save=()=>{if(!outcome){setMessage("Select a review outcome.");outcomeRef.current?.focus();return}if(outcome==="keep-open"&&feedback.trim().length<10){setMessage("Enter at least 10 characters of constructive mentor feedback.");feedbackRef.current?.focus();return}setSaving(true);const now=new Date().toISOString();const reviewOutcome:PocActionResponseReviewOutcome=outcome==="accept"?"accepted":"kept-open";const review:PocActionResponseReview={id:`local-poc-review-${Date.now()}`,actionId:action.id,responseId:response.id,responseVersionId:submitted.id,responseVersion:submitted.version,reviewerName:poc.state.mentorName||"Preview mentor",outcome:reviewOutcome,feedback:feedback.trim(),completeAction:outcome==="accept"&&afterAccept==="complete",reviewedAt:now};poc.commit((state)=>({...state,responseReviews:[...state.responseReviews,review],actions:state.actions.map((entry)=>entry.id===action.id?{...entry,status:outcome==="accept"&&afterAccept==="complete"?"completed":"open",updatedAt:now}:entry)}));onClose()};
  return <Modal title="Review Development Action" size="mentor-review" onClose={requestClose} footer={reviewed?<button type="button" className="btn-ghost" onClick={onClose}>Close</button>:<><button type="button" className="btn-ghost" onClick={requestClose}>Cancel</button><span className="response-footer-status" role="status" aria-live="polite">{message}</span><button type="button" className="btn-primary" disabled={!outcome||saving} onClick={save}>{saving?"Saving…":buttonLabel}</button></>}>
    <div className="mentor-review-form"><div className="action-comment-subtitle">{displayId} · {action.title}</div>
      <section className="mentor-review-section"><h3>Action brief</h3><div className="record-detail"><div><span>Owner</span><strong>{action.owner}</strong></div><div><span>Priority</span><strong>{action.priority}</strong></div><div><span>Due date</span><strong>{action.dueDate||"Not set"}</strong></div><div><span>Status</span><strong>{action.status.replaceAll("-"," ")}</strong></div>{ribaControl}</div><div className="mentor-review-copy"><strong>Action / success criteria</strong><p>{actionDescription}</p><p>{success}</p><small>{competency.reference} · {competency.area} · Active cycle {currentLevel||"not initialised"} · Assigned {date(action.createdAt)}</small></div>{deleteControl}</section>
      <section className="mentor-review-section"><h3>Response being reviewed</h3><div className="mentor-response-meta"><span><b>Candidate</b>{poc.state.candidateName||"Candidate"}</span><span><b>Version</b>{viewVersion.version}</span><span><b>Method</b>{methodLabels[viewVersion.method]||"Legacy response"}</span><span><b>Status</b>{viewVersion.status.replaceAll("-"," ")}</span><span><b>Saved</b>{date(viewVersion.savedAt)}</span><span><b>Submitted</b>{date(viewVersion.submittedAt)}</span></div><div className="mentor-response-sections">{fields.map((field)=>{const value=viewVersion.fields[field.key]?.trim();return value?<article key={field.key}><strong>{field.label}</strong><p>{value}</p></article>:field.optional?null:<article className="empty" key={field.key}><strong>{field.label}</strong><p>Not provided</p></article>})}</div><details className="mentor-quality-context"><summary>Candidate writing guidance result</summary><p>{viewVersion.advisoryQualityScore?`Advisory score ${viewVersion.advisoryQualityScore} of 5.`:"No advisory result was recorded."} This automated result is writing guidance only and does not replace mentor judgement.</p></details>
        <div className="mentor-supporting-grid"><div><h4>Supporting files</h4>{viewVersion.attachments?.length?viewVersion.attachments.map((item)=><div className="mentor-material-row" key={item.id}><span><b>{item.name||"Unnamed file"}</b><small>{item.detail||"File"}{item.size?` · ${(item.size/1024).toFixed(1)} KB`:""}</small></span><em>Metadata only</em></div>):<p className="record-empty-copy">No supporting files supplied.</p>}<small>File metadata is stored locally. File contents are not retained after refresh.</small></div><div><h4>Document links</h4>{viewVersion.documentLinks?.length?viewVersion.documentLinks.map((item)=><div className="mentor-material-row" key={item.id}><span><b>{item.title||"Untitled document"}</b><small>{item.reference||"No reference"}{item.revision?` · ${item.revision}`:""}{item.accessNote?` · ${item.accessNote}`:""}</small></span>{validUrl(item.url)?<a className="btn-ghost" href={item.url} target="_blank" rel="noreferrer">Open</a>:<em>Invalid URL</em>}</div>):<p className="record-empty-copy">No document links supplied.</p>}</div></div>
      </section>
      <details className="mentor-review-section mentor-review-history" open={historyOpen} onToggle={(event)=>setHistoryOpen(event.currentTarget.open)}><summary>Response history · {response.versions.length} version{response.versions.length===1?"":"s"} · {reviews.length} mentor review{reviews.length===1?"":"s"}</summary><div>{[...response.versions].reverse().map((version)=><button type="button" className={viewVersion.id===version.id?"active":""} onClick={()=>setViewVersion(version)} key={version.id}><b>Version {version.version} · {methodLabels[version.method]||"Legacy response"}</b><span>{version.status} · saved {date(version.savedAt)}{version.submittedAt?` · submitted ${date(version.submittedAt)}`:""}</span>{reviews.filter((review)=>review.responseVersionId===version.id).map((review)=><small key={review.id}>{review.outcome} by {review.reviewerName} · {date(review.reviewedAt)}{review.feedback?` · ${review.feedback}`:""}</small>)}</button>)}</div></details>
      <section className="mentor-review-section"><h3>Mentor review</h3><label>Your name (mentor)<input readOnly value={existingReview?.reviewerName||poc.state.mentorName||"Preview mentor"}/></label><label>Mentor feedback<textarea readOnly={reviewed} ref={feedbackRef} rows={5} value={feedback} aria-describedby="mentor-feedback-help" onChange={(event)=>setFeedback(event.target.value)}/><small id="mentor-feedback-help">Explain what was satisfactory, what remains outstanding, or what the candidate must revise.</small></label><label>Review outcome<select disabled={reviewed} ref={outcomeRef} value={outcome} onChange={(event)=>setOutcome(event.target.value as typeof outcome)}><option value="">Select an outcome</option><option value="accept">Accept response</option><option value="keep-open">Keep action open</option></select></label>{outcome==="accept"?<fieldset disabled={reviewed} className="mentor-accept-options"><legend>Action after acceptance</legend><label><input type="radio" name="afterAccept" checked={afterAccept==="keep-open"} onChange={()=>setAfterAccept("keep-open")}/> Keep action open</label><label><input type="radio" name="afterAccept" checked={afterAccept==="complete"} onChange={()=>setAfterAccept("complete")}/> Complete action now</label></fieldset>:null}{outcome==="keep-open"?<p className="mentor-decision-guidance">The review was saved and the action remains open.</p>:null}</section>
    </div>
  </Modal>;
}
